"""Generate the ignored, checkout-specific Codex Desktop MCP configuration."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - exercised by the Python version gate
    print("Codex MCP setup requires Python 3.11 or newer.", file=sys.stderr)
    raise SystemExit(1)


GENERATED_MARKER = "# Generated by .codex/setup_mcp.py; local-only."
MODULE_ARGS = [
    "python",
    "-m",
    "cognivault.transports.mcp_stdio",
    "--config",
    "config.local.toml",
]
LEGACY_RELATIVE_ARGS = ["run", "--project", ".", *MODULE_ARGS]


def _render_config(root: Path, *, template_root: Path | None = None, uv_command: str = "uv") -> str:
    template_path = (template_root or root) / ".codex" / "config.example.toml"
    template = template_path.read_text(encoding="utf-8")
    substitutions = (
        ("__PROJECT_ROOT__", root.as_posix(), 2),
        ("__SOURCE_ROOT__", (root / "src").as_posix(), 1),
        ("__LOCAL_CONFIG_PATH__", (root / "config.local.toml").as_posix(), 1),
    )
    for placeholder, value, expected_count in substitutions:
        quoted_placeholder = json.dumps(placeholder, ensure_ascii=False)
        if template.count(quoted_placeholder) != expected_count:
            raise ValueError(f"Unexpected placeholder count in {template_path.name}.")
        template = template.replace(
            quoted_placeholder, json.dumps(value, ensure_ascii=False)
        )

    if template.count('command = "uv"') != 1:
        raise ValueError("Unexpected uv command in Codex template.")
    template = template.replace('command = "uv"', f"command = {json.dumps(uv_command, ensure_ascii=False)}", 1)
    if uv_command != "uv":
        source = json.dumps((root / "src").as_posix(), ensure_ascii=False)
        original_env = f"env = {{ PYTHONPATH = {source} }}"
        if template.count(original_env) != 1:
            raise ValueError("Unexpected environment in Codex template.")
        environment = json.dumps((root / ".venv").as_posix(), ensure_ascii=False)
        template = template.replace(original_env, f"env = {{ PYTHONPATH = {source}, UV_PROJECT_ENVIRONMENT = {environment} }}", 1)
    generated = f"{GENERATED_MARKER}\n{template}"
    tomllib.loads(generated)
    return generated


def _parse_server(contents: str, name: str = "cognivault") -> dict[str, object] | None:
    try:
        config = tomllib.loads(contents)
        servers = config["mcp_servers"]
        # A dual old/new Gateway registration requires manual review.
        if "cognivault" in servers and "study_system" in servers:
            return None
        server = servers[name]
    except (KeyError, TypeError, tomllib.TOMLDecodeError):
        return None
    return server if isinstance(server, dict) else None


def _has_explicit_checkout_paths(server: dict[str, object], root: Path, *, uv_command: str = "uv") -> bool:
    cwd = server.get("cwd")
    if not isinstance(cwd, str):
        return False
    cwd_path = Path(cwd)
    if not cwd_path.is_absolute() or cwd_path.resolve() != root:
        return False

    expected_absolute_args = [
        "run",
        "--no-sync",
        "--project",
        root.as_posix(),
        *MODULE_ARGS[:-1],
        (root / "config.local.toml").as_posix(),
    ]
    legacy_absolute_args = [
        "run",
        "--project",
        root.as_posix(),
        *MODULE_ARGS[:-1],
        (root / "config.local.toml").as_posix(),
    ]
    current_relative_args = ["run", "--no-sync", "--project", ".", *MODULE_ARGS]
    expected_relative_args = LEGACY_RELATIVE_ARGS
    if uv_command != "uv":
        environment = server.get("env")
        if not isinstance(environment, dict) or environment.get("UV_PROJECT_ENVIRONMENT") != (root / ".venv").as_posix():
            return False
    return (
        server.get("command") == uv_command
        and server.get("args") in (
            expected_absolute_args,
            legacy_absolute_args,
            current_relative_args,
            expected_relative_args,
        )
        and server.get("enabled") is True
        and server.get("required") is True
    )


def _is_owned_generated_config(contents: str, template_root: Path) -> bool:
    if not contents.startswith(f"{GENERATED_MARKER}\n"):
        return False
    server = _parse_server(contents) or _parse_server(contents, "study_system")
    cwd = server.get("cwd") if server else None
    if not isinstance(cwd, str):
        return False
    old_root = Path(cwd)
    if not old_root.is_absolute():
        return False
    try:
        command = server.get("command")
        if not isinstance(command, str) or (
            command != "uv"
            and (
                not Path(command).is_absolute()
                or Path(command).name.casefold() not in {"uv", "uv.exe"}
            )
        ):
            return False
        generated = _render_config(old_root.resolve(), template_root=template_root, uv_command=command)
        previous_generated = generated.replace('    "--no-sync",\n', "", 1)
        # These substitutions reconstruct only the two exact historical helper
        # outputs. The marker alone never grants permission to replace a config.
        legacy_generated = generated.replace(
            "[mcp_servers.cognivault]", "[mcp_servers.study_system]", 1
        ).replace(
            '"cognivault.transports.mcp_stdio"',
            '"chatgpt_study_system.transports.mcp_stdio"', 1,
        )
        legacy_previous = legacy_generated.replace('    "--no-sync",\n', "", 1)
        return contents in (generated, previous_generated, legacy_generated, legacy_previous)
    except (OSError, ValueError):
        return False


def _replace_owned_config(config_path: Path, previous: str, generated: str) -> None:
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=config_path.parent,
            prefix=".config.toml.",
            suffix=".tmp",
            delete=False,
        ) as stream:
            temporary_path = Path(stream.name)
            stream.write(generated)
            stream.flush()
            os.fsync(stream.fileno())

        if config_path.read_text(encoding="utf-8") != previous:
            raise RuntimeError("The local Codex config changed during setup; retry manually.")
        os.replace(temporary_path, config_path)
        temporary_path = None
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--uv", help="Absolute uv executable for a newly installed local runtime.")
    options = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    template_path = root / ".codex" / "config.example.toml"
    config_path = root / ".codex" / "config.toml"
    local_config_path = root / "config.local.toml"

    if not (root / "pyproject.toml").is_file() or not template_path.is_file():
        print("Run this setup script from a complete repository checkout.", file=sys.stderr)
        return 1
    if not local_config_path.is_file():
        print(
            "Create config.local.toml from config.example.toml and configure it before Codex MCP setup.",
            file=sys.stderr,
        )
        return 1
    try:
        tomllib.loads(local_config_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        print("config.local.toml is not readable valid TOML; setup made no changes.", file=sys.stderr)
        return 1
    uv_command = "uv"
    if options.uv:
        uv_path = Path(options.uv)
        if not uv_path.is_absolute() or not uv_path.is_file():
            print("--uv must name an existing absolute executable.", file=sys.stderr)
            return 1
        uv_command = uv_path.resolve().as_posix()
    elif shutil.which("uv") is None:
        print("Install uv and ensure it is on PATH before Codex MCP setup.", file=sys.stderr)
        return 1

    try:
        generated = _render_config(root, uv_command=uv_command)
    except (OSError, ValueError, tomllib.TOMLDecodeError) as exc:
        print(f"Could not render the Codex MCP template: {exc}", file=sys.stderr)
        return 1

    if config_path.exists():
        try:
            existing = config_path.read_text(encoding="utf-8")
        except OSError:
            print("The existing .codex/config.toml is unreadable; it was left unchanged.", file=sys.stderr)
            return 1

        if existing == generated:
            print("Codex MCP is already configured for this checkout; existing file left unchanged.")
            return 0

        if _is_owned_generated_config(existing, root):
            try:
                _replace_owned_config(config_path, existing, generated)
            except (OSError, RuntimeError) as exc:
                print(f"Could not safely refresh the generated Codex config: {exc}", file=sys.stderr)
                return 1
            print("Updated the generated Codex MCP config for this checkout.")
            return 0

        server = _parse_server(existing)
        if server and _has_explicit_checkout_paths(server, root, uv_command=uv_command):
            print("Existing Codex MCP config is compatible with this checkout; file left unchanged.")
            return 0

        print(
            "An unrecognized .codex/config.toml already exists; it was left unchanged. "
            "Review it manually before running setup again.",
            file=sys.stderr,
        )
        return 1

    try:
        with config_path.open("x", encoding="utf-8", newline="\n") as stream:
            stream.write(generated)
    except FileExistsError:
        print("A Codex config appeared during setup; it was left unchanged.", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"Could not create .codex/config.toml: {exc}", file=sys.stderr)
        return 1

    print("Created the ignored .codex/config.toml for this checkout.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
