"""Create a minimal local profile and register Codex without accessing user data."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import subprocess
import sys
import tomllib


def prepare_config(root: Path) -> None:
    config_path = root / "config.local.toml"
    if config_path.exists():
        # Read only the configuration, never its data paths or stores.
        tomllib.loads(config_path.read_text(encoding="utf-8"))
        print("保留已有本地配置，数据位置与权限不变。")
        return
    project = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    version = project["project"]["version"]
    if type(version) is not str or re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", version) is None:
        raise ValueError("项目版本格式无效。")
    contents = (
        "# Generated by the CogniVault installer; local-only.\n"
        "# Optional data locations and capabilities can be configured later.\n\n"
        f'[gateway]\nversion = "{version}"\n\n'
        '[study]\nbackend = "not_configured"\n\n'
        '[history]\nbackend = "not_configured"\n\n'
        '[assets]\nbackend = "not_configured"\n\n'
        '[permissions]\ncapabilities = ["read"]\n'
    )
    with config_path.open("x", encoding="utf-8", newline="\n") as stream:
        stream.write(contents)
    print("已生成默认只读配置，可以稍后接入自己的资料。")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--uv", required=True, help="Absolute uv executable.")
    parser.add_argument("--host", choices=("codex", "none"), default="codex")
    options = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    uv_path = Path(options.uv)
    if not uv_path.is_absolute() or not uv_path.is_file():
        print("安装未完成：找不到指定的 uv 程序，请重新运行安装入口。", file=sys.stderr)
        return 1
    uv_path = uv_path.resolve()
    try:
        prepare_config(root)
        if options.host == "codex":
            result = subprocess.run(
                [sys.executable, "-X", "utf8", str(root / ".codex/setup_mcp.py"),
                 "--uv", str(uv_path)],
                cwd=root, capture_output=True, text=True, encoding="utf-8", timeout=30,
            )
            if result.returncode:
                print("安装未完成：Codex 配置未生成。已有配置已保留。", file=sys.stderr)
                print("请检查 .codex/config.toml 是否存在自定义配置，再重新运行。", file=sys.stderr)
                return 1
    except (OSError, ValueError, KeyError, subprocess.TimeoutExpired):
        print("安装未完成：本地配置无法处理，请检查配置格式与文件写入权限后重试。", file=sys.stderr)
        return 1
    print("\n基础安装完成。")
    if options.host == "codex":
        print("接下来：在 Codex 中打开下面的项目目录，确认信任项目，再新建会话：")
        print(str(root))
        print("向 AI 发送：调用 cognivault 的 health_report，检查当前配置状态。")
        print("尚未验证实际 Codex 会话连接；安装器不会自动更改项目信任。")
    else:
        print("将以下启动参数添加到支持 stdio MCP 的客户端：")
        print(json.dumps({
            "command": uv_path.as_posix(),
            "args": ["run", "--no-sync", "--project", root.as_posix(), "python", "-m",
                     "cognivault.transports.mcp_stdio", "--config", (root / "config.local.toml").as_posix()],
            "cwd": root.as_posix(),
            "env": {"PYTHONPATH": (root / "src").as_posix(),
                    "UV_PROJECT_ENVIRONMENT": (root / ".venv").as_posix()},
        }, ensure_ascii=False, indent=2))
    print("新安装默认尚未接入资料：学习搜索、历史查询和错题保存需按需配置。")
    print("配置说明：docs/installation.md（已有资料配置保持原样）。")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\n已取消，可以稍后重新运行安装入口。", file=sys.stderr)
        raise SystemExit(130)
